### ISSUE TITLE
JuliaCon Proceedings template - how to suppress default pandoc options?

### ISSUE THREAD

**Issue by pat-alt** [quarto-journals/article-format-template#14]
Hi there, 

thanks for this great template and the docs. I've been working on a template for [JuliaCon Proceedings](https://proceedings.juliacon.org/). The repo for the extension can be found here: [https://github.com/pat-alt/quarto-juliacon-proceedings](https://github.com/pat-alt/quarto-juliacon-proceedings).

Most things are already working as expected, but I noted that the character spacing seems off: compare the Quarto [version](https://www.paltmeyer.com/quarto-juliacon-proceedings/examples/CounterfactualExplanations.jl/paper.pdf) to the published [version](https://juliacon.github.io/proceedings-papers/jcon.00130/10.21105.jcon.00130.pdf) of a recent paper.

By sheer luck I noticed that if I comment out the `\usepackage{lmodern}` line in the raw TeX file, the discrepancy disappears. It seems the most straight-forward way to deal with this is to somehow suppress this default option in the `_extension.yml`. Is there a way to do this? Or should this be handled in some other way?

Thanks!

**Comment by pat-alt** [comment]
*Update*: I can set `fontfamily: tgtermes` to get the desired outcome, but would still be interested to know if there is a way to just suppress that line (`\usepackage{lmodern}`). Thanks!

**Comment by cderv** [comment]
`lmodern` is the default font used in the template, and only setting  `fontfamily` will not use it 
https://github.com/quarto-dev/quarto-cli/blob/0a8a3c6bb5ec09809c9c67c77cdf2fbffd422bd6/src/resources/formats/pdf/pandoc/template.tex#L92-L96

```tex
$if(fontfamily)$
$else$
\usepackage{lmodern}
$endif$
```

when setting `fontfamily`, this is will activate this line 
````tex
$if(fontfamily)$
\usepackage[$for(fontfamilyoptions)$$fontfamilyoptions$$sep$,$endfor$]{$fontfamily$}
$endif$
````

so you can't just set `fontfamily` to any value, it must be a package font. 

Otherwise you need to tweak the template in your extension, but unfortunately those part are not inside a partials, so you need to provide a copy of the whole template and maintain it with quarto updates in that case. See https://quarto.org/docs/journals/templates.html

**Comment by pat-alt** [comment]
Ok, thanks @cderv very much for the quick response. Then it seems the below is the easiest approach and I'll stick with that for now:

> _Update_: I can set `fontfamily: tgtermes` to get the desired outcome, but would still be interested to know if there is a way to just suppress that line (`\usepackage{lmodern}`). Thanks!
